### ISSUE TITLE
Add to MatBench?

### ISSUE THREAD

**Issue by sgbaird** [superlouis/GATGNN#3]
https://www.nature.com/articles/s41524-020-00406-3
https://hackingmaterials.lbl.gov/matbench/

**Comment by usccolumbia** [comment]
we have a much improved materials prediction model based on GATGNN. and will release it shortly. 
we will consider to report our performance over your datasets.

**Comment by sgbaird** [comment]
Awesome. Looking forward to it!

**Comment by sgbaird** [comment]
It would be great if you could post the link on this thread so I can get notified of when the new model is released.

**Comment by sgbaird** [comment]
I figured it was worth mentioning some benefits of MatBench. I'm not affiliated with MatBench, but a big part of the appeal is it is a standard benchmark that allows for a one-to-one comparison between models (e.g. same train-val-test splits, same data). In other words, when I go through the GATGNN paper which uses non-standard benchmarks, I can see how it compares to CGCNN and MEGNET for those specific datasets, but it would be non-trivial to see how it compares to any other model (AutoMatminer, CrabNet, ElemNet, Roost, etc.), since I either need to run GATGNN on a dataset that has been run on one of those, or vice-versa. This easily leads to redundant work because it doesn't always get published when someone runs a comparison for themselves. Another huge benefit of MatBench is the visibility. By adding GATGNN to MatBench, people that visit MatBench's website might otherwise never come across GATGNN.

**Comment by usccolumbia** [comment]
yes. read the paper. 
https://arxiv.org/abs/2109.12283
